### PR TITLE
Move where we generate our salt

### LINKED ISSUE #1987: phpredis calls php_random_bytes before random is initialised
### Expected behaviour
`get_random_bytes()` should be called once random has initialized it's `fd` global to -1.

### Actual behaviour
phpredis calls `get_random_bytes()` before `random_globals_ctor()` is called resulting in the `fd` remaining 0. This breaks systems that rely on it (those without a `getrandom()` syscall) as an uninitialised `fd` is expected to be less than 0 (see line 156 in random.c).

### I'm seeing this behaviour on
- OS: CentOS Linux release 7.9.2009
- Redis: 5.0.4
- PHP: 7.4.21
- phpredis: 5.3.2

### Steps to reproduce, backtrace or example script
PHP's internals call GINIT functions before MINIT which describes the behaviour seen here (stepping through the process confirms this).

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

phpredis should call `get_random_bytes()` in it's MINIT to prevent this problem.

### PR DESCRIPTION
**Pull request by michael-grunder**
Fixes #1987

### CODE REVIEW

File: redis.c [hunk 1]
```diff
@@ -425,10 +425,8 @@ static void redis_random_hex_bytes(char *dst, size_t dstsize) {
     zend_string_release(s);
 }
 
-static PHP_GINIT_FUNCTION(redis)
-{
-    redis_random_hex_bytes(redis_globals->salt, sizeof(redis_globals->salt) - 1);
-    redis_globals->salt[sizeof(redis_globals->salt)-1] = '\0';
+/* We don't currently use this callback but may in the future */
```
Comment (yatsukhnenko) [inline redis.c]: Let's remove this callback and add in future if needed 🙂

**Review by yatsukhnenko — APPROVED** [review]
