### PR TITLE
Fix hset fields handling

### LINKED ISSUE #2670: hSet hangs if associative array is passed in some cases
Hello and thanks for the great PhpRedis!

I would like to report a bug.
PHP 8.4
php-redis 6.2

If the method is called and an associative array is passed like the following:
... ->hSet('test_key', $assocArr);

and the associative array has at least one INT value in its keys like the following:
[1 => 'asdasd'] or even as a string ['1' => 'asdasd']

the script execution hangs on this method.

The issue repeats with the latest code from the git repo.

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Fixes #2670

As described in issue fields may be specified as associative array with mix string and integer keys so in this case integer fields skipped and command become inconsistent (less number of arguments than in header)

### CODE REVIEW

File: redis_commands.c [hunk 1]
```diff
@@ -3543,12 +3544,14 @@ int redis_hset_cmd(INTERNAL_FUNCTION_PARAMETERS, RedisSock *redis_sock,
...
 
-        ZEND_HASH_FOREACH_STR_KEY_VAL(Z_ARRVAL_P(args), zkey, z_ele) {
-            if (zkey != NULL) {
-                ZVAL_DEREF(z_ele);
-                redis_cmd_append_sstr(&cmdstr, ZSTR_VAL(zkey), ZSTR_LEN(zkey));
-                redis_cmd_append_sstr_zval(&cmdstr, z_ele, redis_sock);
+        ZEND_HASH_FOREACH_KEY_VAL(Z_ARRVAL_P(args), idx, zkey, z_ele) {
+            ZVAL_DEREF(z_ele);
+            if (zkey == NULL) {
+                redis_cmd_append_sstr_zstr(&cmdstr, key);
```
Comment (michael-grunder) [inline redis_commands.c]:
```suggestion
                redis_cmd_append_sstr_long(&cmdstr, idx);
```

**Review by michael-grunder — CHANGES_REQUESTED** [review]
I don't think we want to add the key name as the field :smile:

**Review by michael-grunder — APPROVED** [review]
