### PR TITLE
Fix #1952 Incorrect PHP method info on the RedisCluster time method

### LINKED ISSUE #1952: Incorrect PHP method info on the RedisCluster time method
### Expected behaviour
Reflection on the RedisCluster `time` method returns `key_or_address`

### Actual behaviour
`time` method has `arginfo_void`, expected to be the same as for example the save method `arginfo_key_or_address`
https://github.com/phpredis/phpredis/blob/develop/redis_cluster.c#L250

### I'm seeing this behaviour on
- OS: Ubuntu 20.04
- Redis: 6.2.1
- PHP: 8.0.3
- phpredis: 5.3.2

### Steps to reproduce, backtrace or example script
```
 $nodes = ['127.0.0.1:7001', '127.0.0.1:7002', '127.0.0.1:7003'];
 $redis = new RedisCluster(null, $nodes, 9, 9);

$reflect = new ReflectionClass($redis);
var_dump($reflect->getMethod('time')->getParameters());
var_dump($reflect->getMethod('save')->getParameters());
// Result:
//   array(1) {
//     [0]=>
//       object(ReflectionParameter)#99 (1) {
//         ["name"]=>
//       string(14) "key_or_address"
//     }
//   }
//   array(0) {
//   }
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

### PR DESCRIPTION
**Pull request by sudo-plz**
Fixes [#1952](https://github.com/phpredis/phpredis/issues/1952)

### CODE REVIEW

File: redis_cluster.c [hunk 1]
```diff
@@ -247,7 +247,7 @@ zend_function_entry redis_cluster_functions[] = {
     PHP_ME(RedisCluster, subscribe, arginfo_subscribe, ZEND_ACC_PUBLIC)
     PHP_ME(RedisCluster, sunion, arginfo_nkeys, ZEND_ACC_PUBLIC)
     PHP_ME(RedisCluster, sunionstore, arginfo_dst_nkeys, ZEND_ACC_PUBLIC)
-    PHP_ME(RedisCluster, time, arginfo_void, ZEND_ACC_PUBLIC)
+    PHP_ME(RedisCluster, time, key_or_address, ZEND_ACC_PUBLIC)
```
Comment (yatsukhnenko) [inline redis_cluster.c]: It has to be `arginfo_key_or_address`

**Review by yatsukhnenko — CHANGES_REQUESTED** [review]

File: redis_cluster.c (hunk 1 above)
Comment (sudo-plz) [reply redis_cluster.c]: Ah ... sorry 🙈 .
