### PR TITLE
Print cursor as unsigned 64 bit integer

### LINKED ISSUE #2600: Problems with large cursors when scanning using RedisCluster
### Expected behaviour
Scans using `RedisCluster` that specify a large cursor should return results and update the cursor.

### Actual behaviour
`RedisClusterException` with the message "Couldn't process SCAN response from node" is thrown.

`RedisCluster` says the last error was "ERR invalid cursor".

### I'm seeing this behaviour on
- OS: Alpine Linux amd64 
- Redis: 7.1 (cluster mode and Amazon ElastiCache)
- PHP: 8.3.8
- phpredis: 6.1.0

### Steps to reproduce, backtrace or example script
Running the following PHP script:
```
try {
    $node = $redisCluster->_masters()[0];
    $it = null;
    do {
        var_dump($redisCluster->scan($it, $node, 'laravel_database_app-api-au-*', 20));
        var_dump($iterator);
    } while ($it !== 0);
} catch (\RedisClusterException $e) {
    var_dump($e);
}
```

The script returns the first scan correctly. The iterator is then updated to the string "9286422431638134784" which is expected from the changes in 6.1.0.

However, when the second scan is attempted the exception is thrown and that "ERR invalid cursor" message is happening.

To double check this isn't an issue with redis itself I attempted:
```
scan 0 match "laravel_database_app-api-au-*" count 20
```

Which returned the first page correctly and a similar cursor "9286422431638396928".
I then ran:
```
scan "9286422431638396928" match "laravel_database_app-api-au-*" count 20
```

It returned a new page of results and a new cursor value.

### I've checked
- [x ] There is no similar issue from other users
  - There's some discussion in #2562 but it's more about the initial cursor value (no longer works with the string `"0"`)
- [ ] Issue isn't fixed in `develop` branch

### PR DESCRIPTION
**Pull request by bentleyo**
Prevent cursor from being converted from an unsigned 64-bit integer to a long (and therefore truncated in some situations) when the redis command is generated.

Should fix #2600.

Am I able to get some help testing this? I'm not very familiar with C, I spend too much time in PHP land 🙈

### CODE REVIEW

**Comment by michael-grunder** [comment]
Great job, I will get this merged in the morning

**Comment by bentleyo** [comment]
I managed to test my changes by building the extension for our staging environment.

I can confirm it's no longer throwing an invalid cursor error when using a large cursor 😊

File: library.c [hunk 1]
```diff
@@ -1065,6 +1065,15 @@ int redis_cmd_append_sstr_i64(smart_string *str, int64_t append) {
     return redis_cmd_append_sstr(str, nbuf, len);
 }
 
+/*
+ * Append a 64-bit unsigned integer to our command
+ */
+int redis_cmd_append_sstr_ui64(smart_string *str, uint64_t append) {
+    char nbuf[64];
```
Comment (michael-grunder) [inline library.c]:
```suggestion
    char nbuf[21];
```

strlen(18446744073709551615) = 20 + 1 for '\0'

File: library.c [hunk 2]
```diff
@@ -1065,6 +1065,15 @@ int redis_cmd_append_sstr_i64(smart_string *str, int64_t append) {
     return redis_cmd_append_sstr(str, nbuf, len);
 }
 
+/*
+ * Append a 64-bit unsigned integer to our command
+ */
+int redis_cmd_append_sstr_ui64(smart_string *str, uint64_t append) {
```
Comment (michael-grunder) [inline library.c]:
```suggestion
int redis_cmd_append_sstr_u64(smart_string *str, uint64_t append) {
```

File: library.h [hunk 3]
```diff
@@ -50,6 +50,7 @@ int redis_cmd_append_sstr(smart_string *str, char *append, int append_len);
 int redis_cmd_append_sstr_int(smart_string *str, int append);
 int redis_cmd_append_sstr_long(smart_string *str, long append);
 int redis_cmd_append_sstr_i64(smart_string *str, int64_t append);
+int redis_cmd_append_sstr_ui64(smart_string *str, uint64_t append);
```
Comment (michael-grunder) [inline library.h]:
```suggestion
int redis_cmd_append_sstr_u64(smart_string *str, uint64_t append);
```

File: redis_commands.c [hunk 4]
```diff
@@ -591,7 +591,7 @@ int redis_fmt_scan_cmd(char **cmd, REDIS_SCAN_TYPE type, char *key, int key_len,
     }
 
     // Append cursor
-    redis_cmd_append_sstr_long(&cmdstr, it);
+    redis_cmd_append_sstr_ui64(&cmdstr, it);
```
Comment (michael-grunder) [inline redis_commands.c]:
```suggestion
    redis_cmd_append_sstr_u64(&cmdstr, it);
```

File: library.c (hunk 1 above)
Comment (bentleyo) [reply library.c]: @michael-grunder nice! I reduced `redis_cmd_append_sstr_i64` to `21` too.

The longest number it can represent is `-9223372036854775808` (including the sign is 20 characters) + `\0` I believe.

**Comment by bentleyo** [comment]
@michael-grunder is this something that will go out as part of the next minor release (it looks like there's a fair amount of stuff there)? Or will it be a patch for `6.1.0`?

**Comment by michael-grunder** [comment]
It'll go out in `6.1.1` which should be pretty soon.
